// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <libkern/OSByteOrder.h>
#include <pwd.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

#define htobe16(x) OSSwapHostToBigInt16(x)
#define htobe32(x) OSSwapHostToBigInt32(x)
#define htobe64(x) OSSwapHostToBigInt64(x)
#define le16toh(x) OSSwapLittleToHostInt16(x)
#define htole16(x) OSSwapHostToLittleInt16(x)

#define CARRY_FLAG_BIT 1
#define RETURN_SYSCALL_RESULT(result, flags) return (flags & CARRY_FLAG_BIT) ? -result : result;
__attribute__((noinline)) static int64_t __syscall(int64_t num, int64_t arg1, int64_t arg2, int64_t arg3, int64_t arg4, int64_t arg5, int64_t arg6, int64_t arg7, int64_t arg8, int64_t arg9)
{
	int64_t result;
	int64_t flags;
	// le than mach _syscalls
	if (num < 0x1000000)
		num += 0x2000000;

	__asm__ __volatile__(
        "subq $0x18, %%rsp\n"
	    "movq %6, %%r10;\n"
	    "movq %7, %%r8;\n"
	    "movq %8, %%r9;\n"
	    "movq %9, %%r11\n"
	    "movq %%r11, 0(%%rsp)\n"
	    "movq %10, %%r11\n"
	    "movq %%r11, 0x8(%%rsp)\n"
        "movq %11, %%r11\n"
        "movq %%r11, 0x10(%%rsp)\n"
	    "syscall;\n"
        "addq $0x18, %%rsp\n"
	    "movq %%r11, %1;\n"
	    : "=a"(result), "=r"(flags)
	    : "a"(num), "D"(arg1), "S"(arg2), "d"(arg3), "r"(arg4), "r"(arg5), "r"(arg6), "m"(arg7), "m"(arg8), "m"(arg9)
	    : "%r10", "%r8", "%r9", "%rcx", "%r11", "memory");

	RETURN_SYSCALL_RESULT(result, flags);
}

#define GET_SYSCALL_MACRO(_0,_1,_2,_3,_4,_5,_6,_7,_8,_9, NAME, ...) NAME

#define _syscall(...) \
    GET_SYSCALL_MACRO(__VA_ARGS__, \
                        _syscall9, \
                        _syscall8, \
                        _syscall7, \
                      _syscall6, \
                      _syscall5, \
                      _syscall4, \
                      _syscall3, \
                      _syscall2, \
                      _syscall1, \
                      _syscall0) (__VA_ARGS__)

long _syscall0(long n) {
    return __syscall(n, 0, 0, 0, 0, 0, 0, 0, 0, 0);
}
long _syscall1(long n, long a1) {
    return __syscall(n, a1, 0, 0, 0, 0, 0, 0, 0, 0);
}
long _syscall2(long n, long a1, long a2) {
    return __syscall(n, a1, a2, 0, 0, 0, 0, 0, 0, 0);
}
long _syscall3(long n, long a1, long a2, long a3) {
    return __syscall(n, a1, a2, a3, 0, 0, 0, 0, 0, 0);
}
long _syscall4(long n, long a1, long a2, long a3, long a4) {
    return __syscall(n, a1, a2, a3, a4, 0, 0, 0, 0, 0);
}
long _syscall5(long n, long a1, long a2, long a3, long a4, long a5) {
    return __syscall(n, a1, a2, a3, a4, a5, 0, 0, 0, 0);
}
long _syscall6(long n, long a1, long a2, long a3, long a4, long a5, long a6) {
    return __syscall(n, a1, a2, a3, a4, a5, a6, 0, 0, 0);
}
long _syscall7(long n, long a1, long a2, long a3, long a4, long a5, long a6, long a7) {
    return __syscall(n, a1, a2, a3, a4, a5, a6, a7, 0, 0);
}
long _syscall8(long n, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8) {
    return __syscall(n, a1, a2, a3, a4, a5, a6, a7, a8, 0);
}
long _syscall9(long n, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9) {
    return __syscall(n, a1, a2, a3, a4, a5, a6, a7, a8, a9);
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
                _syscall(SYS_mmap, /*addr=*/0x200000000ul, /*len=*/0x1000000ul, /*prot=PROT_WRITE|PROT_READ*/3ul, /*flags=MAP_PRIVATE|MAP_FIXED|MAP_ANON*/0x1012ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
        const char* reason;
        (void)reason;
                                intptr_t res = 0;
        if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {}
//  kqueue arguments: [
//  ]
//  returns kqueue
        res = _syscall(SYS_kqueue);
        for (int i = 0; i < 64; i++) {
        _syscall(SYS_kqueue);
        }
        if (res != -1)
                r[0] = res;
//  kevent arguments: [
//    kqueue: kqueue (resource)
//    changelist: ptr[in, array[kevent]] {
//      array[kevent] {
//        kevent {
//          ident: intptr = 0xfff (8 bytes)
//          filter: filters = 0xfffffffffffffffd (2 bytes)
//          flags: evflags = 0xc079 (2 bytes)
//          fflags: fflags = 0x1 (4 bytes)
//          data: int64 = 0x1 (8 bytes)
//          udata: intptr = 0x8 (8 bytes)
//          ext: array[int64] {
//            int64 = 0x1 (8 bytes)
//            int64 = 0x10 (8 bytes)
//            int64 = 0x3 (8 bytes)
//            int64 = 0x2 (8 bytes)
//          }
//        }
//      }
//    }
//    nchanges: len = 0x1 (8 bytes)
//    eventlist: nil
//    nevents: len = 0x0 (8 bytes)
//    timeout: nil
//  ]
*(uint64_t*)0x200005640 = 0xfff;
*(uint16_t*)0x200005648 = 0xfffd;
*(uint16_t*)0x20000564a = 0xc079;
*(uint32_t*)0x20000564c = 1;
*(uint64_t*)0x200005650 = 1;
*(uint64_t*)0x200005658 = 8;
*(uint64_t*)0x200005660 = 1;
*(uint64_t*)0x200005668 = 0x10;
*(uint64_t*)0x200005670 = 3;
*(uint64_t*)0x200005678 = 2;
        _syscall(SYS_kevent, /*kqueue=*/r[0], /*changelist=*/0x200005640ul, /*nchanges=*/1ul, /*eventlist=*/0ul, /*nevents=*/0ul, /*timeout=*/0ul);
        for (int i = 0; i < 64; i++) {
        _syscall(SYS_kevent, /*kqueue=*/r[0], /*changelist=*/0x200005640ul, /*nchanges=*/1ul, /*eventlist=*/0ul, /*nevents=*/0ul, /*timeout=*/0ul);
        }
        return 0;
}